default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test